config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', views.index, name='index'),
    path('myprofile/', include('myprofile.urls')),
    path('admin/', admin.site.urls),
]

# 画像パス設定
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myprofile/urls.py
from django.urls import path

from . import views

app_name = 'myprofile'
urlpatterns = [
    path('', views.Index, name='index'),
    path('workdetail/<int:work_id>/', views.WorkDetail, name='work_detail'),
]

myprofile/models.py
from django.db import models
from django.utils import timezone
# Create your models here.


class Content(models.Model):
    title = models.CharField(max_length=200, default="")
    sub_title = models.CharField(max_length=200, blank=True, default="")
    main_text = models.TextField(max_length=1000, blank=True, default="")
    main_text_english = models.TextField(max_length=1000, blank=True, default="")
    contents_type = models.CharField(max_length=20, default="SITE")
    date_created = models.DateTimeField(default=timezone.now)
    date_changed = models.DateTimeField(default=timezone.now)
    avator = models.ImageField(verbose_name='avator', upload_to='myprofile/', blank=True, default="")

    def __str__(self):
        return self.title


class Skill(models.Model):
    content = models.ForeignKey(Content, on_delete=models.CASCADE, related_name="related_content")
    name = models.CharField(max_length=200, default="")
    rank = models.IntegerField(default=0)
    type = models.CharField(max_length=20, default="")
    date_created = models.DateTimeField(default=timezone.now)
    date_changed = models.DateTimeField(default=timezone.now)


class Work(models.Model):
    content = models.ForeignKey(Content, on_delete=models.CASCADE, related_name="work_content")
    name = models.CharField(max_length=200, default="")
    top_image = models.ImageField(verbose_name='top_image', upload_to='myprofile/')
    date_created = models.DateTimeField(default=timezone.now)
    date_changed = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name


class SubWork(models.Model):
    work = models.ForeignKey(Work, on_delete=models.CASCADE, related_name="sub_work_content")
    main_text = models.TextField(max_length=1000, blank=True, default="")
    sub_text = models.TextField(max_length=1000, blank=True, default="")
    sub_image_1 = models.ImageField(verbose_name='sub_image_1', upload_to='myprofile/', blank=True, default="")
    sub_image_2 = models.ImageField(verbose_name='sub_image_1', upload_to='myprofile/', blank=True, default="")
    sub_image_3 = models.ImageField(verbose_name='sub_image_1', upload_to='myprofile/', blank=True, default="")
    sub_image_4 = models.ImageField(verbose_name='sub_image_1', upload_to='myprofile/', blank=True, default="")
    sub_image_5 = models.ImageField(verbose_name='sub_image_1', upload_to='myprofile/', blank=True, default="")
    link = models.CharField(max_length=500, blank=True, default="")
    date_created = models.DateTimeField(default=timezone.now)
    date_changed = models.DateTimeField(default=timezone.now)


class Contact(models.Model):
    name = models.CharField(max_length=50)
    mail = models.CharField(max_length=100)
    text = models.TextField(max_length=1000)
    date_created = models.DateTimeField(default=timezone.now)

config/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')

myprofile/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect
from django.template import loader
from .models import Content, SubWork, Work
from .Form.contactForm import ContactForm
# Create your views here.


def Index(request):
    about_sites = Content.objects.filter(contents_type="SITE").first()
    about_me = Content.objects.filter(contents_type="PROFILE").first()
    skills = Content.objects.filter(contents_type="SKILLS").first()
    skill_db = skills.related_content.filter(type="DB").order_by("name")
    skill_language = skills.related_content.filter(type="Language").order_by("name")
    skill_framework = skills.related_content.filter(type="Framework").order_by("name")
    works = Content.objects.filter(contents_type="WORKS").first()
    work_contents = works.work_content.all()
    template = loader.get_template('myprofile/index.html')

    # 問い合わせフォーム
    contact_form = ContactForm()
    isSuccess = False
    if request.method == "POST":
        contact_form = RegisterContact(request)

    # 水玉用
    for_range_li = [i for i in range(15)]

    # テーブルのレイアウトをそろえる用の変数
    skill_max_count = max([len(skill_db), len(skill_language), len(skill_framework)])
    for_range_skill_db = [i for i in range(skill_max_count - len(skill_db))]
    for_range_skill_language = [i for i in range(skill_max_count - len(skill_language))]
    for_range_skill_framework = [i for i in range(skill_max_count - len(skill_framework))]

    context = {
        'about_sites': about_sites,
        'about_me': about_me,
        'skills': skills,
        'skill_db': skill_db,
        'skill_language': skill_language,
        'skill_framework': skill_framework,
        'works': works,
        'work_contents': work_contents,
        'for_range_skill_db': for_range_skill_db,
        'for_range_skill_language': for_range_skill_language,
        'for_range_skill_framework': for_range_skill_framework,
        'for_range_li': for_range_li,
        'contact_form': contact_form,
        'isSuccess': isSuccess,
    }
    return HttpResponse(template.render(context, request))


def WorkDetail(request, work_id):
    if request.method == 'GET':
        work = Work.objects.filter(pk=work_id)
        work_detail = SubWork.objects.filter(work_id=work[0].pk)
        img_url_root = work[0].top_image.url[:work[0].top_image.url.find("/", 1) + 1]
        work = list(work.values())
        work_detail = list(work_detail.values())
        context = {
            'work': work[0],
            'img_url_root': img_url_root,
            'work_detail': work_detail[0],
        }
        return JsonResponse(context)


def RegisterContact(request):
    if request.method == "POST":
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            post = contact_form.save()
            post.author = request.user
            post.save()
            contact_form.SendContactMail()
            return ContactForm()
    return contact_form

templates/index.html
bbbb

templates/myprofile/aboutMe.html
{% load static %}
<div class="section about-me" id="about-me">
	<div class="contents">
		<h1 class="title">{{ about_me.title }}</h1>
		<h2 class="sub-title">{{ about_me.sub_title }}</h2>
		<br/>
		<div class="flex-wrapper">
			<div class="img-contents">
				<img src="{{ about_me.avator.url }}" class="my-img">
			</div>
			<div class="main">
				{{ about_me.main_text | linebreaks }}
				<br/>
			</div>
		</div>
	</div>
</div>

templates/myprofile/aboutSite.html
<div class="section area" id="home">
    <div class="about-site">
        <h1 class="title">{{ about_sites.title }}</h1>
        <h2 class="sub-title">{{ about_sites.sub_title }}</h2>
        <div class="wrapper-main">
            <div class="main">
                {{ about_sites.main_text | linebreaks }}
                <br/>
            </div>
            <div class="main-english">
                {{ about_sites.main_text_english | linebreaks }}
            </div>
        </div>
    </div>
    <ul class="circles">
        {% for i in for_range_li %}
            <li></li>
        {% endfor %}
    </ul>
</div>

templates/myprofile/contact.html
{% load static %}
<div class="section contact" id="contact">
	<div class="contents">
		<h1 class="title">Contact</h1>
        <div class="contact-form">
            {% if contact_form.errors %}
                {% for error in contact_form.non_field_errors %}
                {{ error }}
                {% endfor %}
            {% endif %}
		    {% block content %}
            <form method="POST" name="form1" class="post-form">
                {% csrf_token %}
                <table cellspacing="10">
                    {{ contact_form.as_table }}
                </table>
                <div class="button">
                    <a href="javascript:form1.submit()" class="save btn btn-default">Send</a>
                </div>
            </form>
            {% endblock %}
        </div>
	</div>
</div>

templates/myprofile/footer.html
<footer>
    <p>
        (c) 2022 Nosuke
    </p>
</footer>

templates/myprofile/header.html
<header>
    <nav>
        <div class="navi">
            <ul class="navi-list">
                <li><a href="#home">HOME</a></li>
                <li><a href="#about-me">Profile</a></li>
                <li><a href="#skills">Skill</a></li>
                <li><a href="#works">Work</a></li>
                <li><a href="#contact">Contact</a></li>
                <!--<li><a href="#blog" style="color: gray;">Blog</a></li>-->
            </ul>
        </div>
    </nav>
</header>

templates/myprofile/index.html
<!DOCTYPE html>
<html lang="ja">
{% load static %}
{% load sass_tags %}
<head>
	<meta charset="utf-8">
	<title>Nosuke Profile</title>
	<meta name="description" content="Miwa Ryunosukeのポートフォリオ兼ブログサイト">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="{% static 'myprofile/css/background.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'myprofile/css/base.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'myprofile/css/aboutSite.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'myprofile/css/aboutMe.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'myprofile/css/skills.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'myprofile/css/works.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'myprofile/css/modal.css' %}">
	<link rel="stylesheet" type="text/css" href="{% sass_src 'myprofile/scss/star_rate.scss' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'myprofile/css/contact.css' %}">
</head>
<body>
	<div class="wrapper">
	<!----- header----->
	{% include "myprofile/header.html" %}
	<!----- /header ----->
	<!----- main ----->
	{% include "myprofile/aboutSite.html" %}
	{% include "myprofile/aboutMe.html" %}
	{% include "myprofile/skills.html" %}
	{% include "myprofile/works.html" %}
	{% include "myprofile/contact.html" %}
	<!----- /main ----->

	<!----- footer ----->
	{% include "myprofile/footer.html" %}
	<!----- /footer ----->
	</div>
</body>
</html>

templates/myprofile/skills.html
{% load static %}
{% load custom_tag %}
<div class="section skills" id="skills">
    <div class="contents">
		<h1 class="title">{{ skills.title }}</h1>
		<h2 class="sub-title">{{ skills.sub_title }}</h2>
		<br/>
		<div class="main">
			{{ skills.main_text | linebreaks }}
			<br/>
		</div>
        <div class="flex-wrapper-skills">
            <div class="skill-set">
                <table class="skill-table">
                    <thead>
                        <tr>
                            <th colspan="2">DB</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for skill_set in skill_db %}
                            <tr>
                                <td class="skill-name">{{skill_set.name}}</td>
                                <td class="skill-rank star-rating" data-rate="{{ skill_set.rank }}"></td>
                            </tr> 
                        {% endfor %}
                        {% for i in for_range_skill_db %}
                            <tr>
                                <td class="skill-name"><br/></td>
                                <td class="skill-rank"><br/></td>
                            </tr> 
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="skill-set">
                <table class="skill-table">
                    <thead>
                        <tr>
                            <th colspan="2">Language</th>
                        </tr>
                    </thead>
                    <tbody>    
                        {% for skill_set in skill_language %}
                            <tr>
                                <td class="skill-name">{{skill_set.name}}</td>
                                <td class="skill-rank star-rating" data-rate="{{ skill_set.rank }}"></td>
                            </tr> 
                        {% endfor %}
                        {% for i in for_range_skill_language %}
                            <tr>
                                <td class="skill-name"><br/></td>
                                <td class="skill-rank"><br/></td>
                            </tr> 
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="skill-set">
                <table class="skill-table">
                    <thead>
                        <tr>
                            <th colspan="2">Framework</th>
                        </tr>
                    </thead>
                    <tbody>  
                        {% for skill_set in skill_framework %}
                            <tr>
                                <td class="skill-name">{{skill_set.name}}</td>
                                <td class="skill-rank star-rating" data-rate="{{ skill_set.rank }}"></td>
                            </tr> 
                        {% endfor %}
                        {% for i in for_range_skill_framework %}
                            <tr>
                                <td class="skill-name"><br/></td>
                                <td class="skill-rank"><br/></td>
                            </tr> 
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

templates/myprofile/works.html
{% load static %}
<div class="section works" id="works">
    <div class="contents">
		  <h1 class="title">{{ works.title }}</h1>
		  <h2 class="sub-title">{{ works.sub_title }}</h2>
		  <br/>
		  <div class="main">
			  {{ works.main_text | linebreaks }}
			  <br/>
		</div>
    <div class="flexbox">
      {% for contents in work_contents %}
        <div class="item">
          <!--<a href="{% url 'myprofile:work_detail' 0 %}" onclick="modalOpen()">-->
            <img class="work-img" src="{{ contents.top_image.url }}" id="works_{{ contents.id }}" onclick="getWorkDetail('{{ contents.id }}')">
          <!--</a>-->
          {{ contents.name }}
        </div>
      {% endfor %}
    </div>
	</div>
  <div class="modal" id="modal">
    <div class="modal-contents">
      <p id="error-message"></p>
        <div class="modal-flex">
            <div class="modal-explanation">
                <div class="modal-outline">
                    <h1 id="work-name"></h1>
                    <p id="work-text"></p>
                </div>
                <div class="modal-use-list">
                    <h1>使用技術等</h1>
                    <p id="work-skill"></p>
                </div>
            </div>
            <div class="modal-img">
                <div class="modal-img-list" id="sub-imgs">
                </div>
                <div class="modal-img-main">
                  <a id="main-link" href=""><img class="main-img" id="main-img"></a>
                </div>
            </div>
        </div>
    </div>
  </div>
</div>
<script>

  // 仕事詳細をjsonで取得
  function getWorkDetail(id) {
      var xhr = new XMLHttpRequest();
      {% autoescape off %}
      var url = "{% url 'myprofile:work_detail' 0 %}".replace('0', id)
      {% endautoescape %}
      xhr.open("GET", url);
      xhr.onreadystatechange  = function (e) {
          if (xhr.readyState === 4) {
              if (xhr.status === 200) {
                  // 処理
                  let data = JSON.parse(xhr.responseText);
                  setWorkDetail(data);
                  modalOpen();
                  document.body.classList.add('no-scroll');
              } else {
                  //
              }
          }
      };
      xhr.send();
  }

  function changeMainImg(id) {
    main_img = document.getElementById('main-img');
    sub_img = document.getElementById(id);
    main_img.src = sub_img.src;
  }

  function setWorkDetail(data) {
    work_name = document.getElementById('work-name');
    work_text = document.getElementById('work-text');
    work_skill = document.getElementById('work-skill');
    sub_imgs = document.getElementById('sub-imgs');
    main_img = document.getElementById('main-img');
    main_link = document.getElementById('main-link');
    sub_img_0 = document.getElementById('sub-img-0');
    work_name.textContent = data.work.name;
    work_text.innerHTML = data.work_detail.main_text.replace(/\r?\n/g, '<br>');
    work_skill.innerHTML = data.work_detail.sub_text.replace(/\r?\n/g, '<br>');
    main_img.src =  data.img_url_root + data.work.top_image;
    main_link.href = data.work_detail.link;
    if ((data.work_detail.link === null) || (data.work_detail.link === ""))
    {
      main_link.classList.add("link-none")
    }
    else if (main_link.classList.contains("link-none"))
    {
      main_link.classList.remove("link-none")
    }

    // 1個目はメイン画像
    if (sub_img_0 == null)
    {
      sub_imgs.innerHTML += '<img  class="sub-img" id="sub-img-0" src="' + main_img.src + '" onclick="changeMainImg(\'sub-img-0\')" >';
    }
    else
    {
      sub_img_0.src = main_img.src;
    }

    for (var i = 1; i <= 5; i++)
    {
      let id = "sub-img-" + i;
      let src = data.img_url_root + data.work_detail['sub_image_' + i];
      let event = "changeMainImg(\'" + id + "\')";

      // 追加
      if (typeof sub_imgs.children[i] === 'undefined')
      {
        if ((data.work_detail['sub_image_' + i] != ''))
        {
          sub_imgs.innerHTML += '<img  class="sub-img" id="' + id + '" src="' + src + '" onclick="' + event + '" >';
        }
      }
      else
      {
        // 変更
        if ((data.work_detail['sub_image_' + i] != ''))
        {
          sub_img = document.getElementById(id);
          sub_img.src = src;
        }
        // 削除
        else
        {
          let element = document.getElementById(id);
          if (element != null)
          {
            element.remove();
          }
        }
      }
    }
  }
      
  // モーダルを開く
  function modalOpen() {
    const modal = document.getElementById('modal');
    modal.style.display = 'block';
  }

  // モーダルコンテンツ以外がクリックされた時閉じる
  addEventListener('click', outsideClose);
  function outsideClose(e) {
    if (e.target == modal) {
        modal.style.display = 'none';
        document.body.classList.remove('no-scroll');
    }
  }

</script>